### ISSUE TITLE
How to build this engine?

### ISSUE THREAD

**Issue by orklann** [mortennobel/SimpleRenderEngine#13]
I looked around the project, but I am hardly to find any way to build this engine, especially on macOS or Windows 7, any help?

**Comment by mortennobel** [comment]
Currently the project is only distributed as source code and you have to build the static library yourself (and link it to a project). This is done in a two step process, where you first generate project files using CMake and then build the library using XCode/Visual Studio (the build target from CMake).

https://mortennobel.github.io/SimpleRenderEngine/#download-and-setup-simplerenderengine

SimpleRenderEngine has a number of dependencies (such as SDL, SDL Image, etc). If you just want an easy way to get started with SimpleRenderEngine, I recommend that you download the Github project SimpleRenderEngine Project, which includes all dependencies and CMake has the correct paths. 

https://github.com/mortennobel/SimpleRenderEngineProject

**Comment by orklann** [comment]
Thanks for the reply.
