### ISSUE TITLE
Error compiling sre

### ISSUE THREAD

**Issue by AssociationSirius** [mortennobel/SimpleRenderEngine#15]
On ubuntu 16.04 LTS, gcc version 5.4.0 20160609, i have this error :

Texture.cpp:126:70: error: ‘SDL_PIXELFORMAT_RGBA32’ was not declared in this scope
alpha ?SDL_PIXELFORMAT_RGBA32 : SDL_PIXELFORMAT_RGB24, 0);

**Comment by mortennobel** [comment]
Fixed in 0.9.17
