### ISSUE TITLE
RenderPass failure when using plain Renderer (missing initialization?)

### ISSUE THREAD

**Issue by codewing** [mortennobel/SimpleRenderEngine#41]
I've been trying to use the Renderer class directly without the use of the SDLRenderer because the latter didn't allow to split the engine into different systems like rendering / IO / ...

But when I create a RenderPass I end up with a corrupted stack. All the other examples seemed to work fine though.

I create the Renderer with a pointer to the SDL_Window and vsync false and my render loop looks like this (see: SimpleRenderer.cpp in the attached zip):
```c++
    auto cameraObj = ObjectManager::GetInstance()->getCameraManager().GetActiveCamera();

    auto rp = sre::RenderPass::create()
            .withCamera(*cameraObj)
            .build();

    auto spriteBatchBuilder = sre::SpriteBatch::create();
    for (auto& renderComp : ObjectManager::GetInstance()->getRenderableComponents()){
        renderComp->renderSprite(spriteBatchBuilder);
    }

    auto sb = spriteBatchBuilder.build();
    rp.draw(sb);
```

Full project: [master.zip](https://github.com/mortennobel/SimpleRenderEngine/files/2612405/master.zip)
On linux It crashes at line 386: `glLinkProgram(g_ShaderHandle);` in `imgui_sre.cpp`
On windows it crashes at the end of the same method.

---

- Is there some code which has to be executed for initialization that I'm missing?
- Is there an example on how to use the plain Renderer?

**Comment by codewing** [comment]
I've tried it with the code from the hello-engine-raw example and I'm facing the same error
   ```c++
 RenderPass rp = RenderPass::create().build();
 rp.drawLines({{0,0,0},{1,1,1}});
 rp.finish();
 r.swapWindow();
```

**Comment by mortennobel** [comment]
You are right that hello-engine-raw has an issue (on Windows).

The problem is that glew need to be used to initialize an OpenGL context after the window has been created (see SDLRenderer)

**Comment by codewing** [comment]
But I'm facing the same errror on linux and the Renderer _successfully_ calls the create context
`glcontext = SDL_GL_CreateContext(window);` on line 49 in Renderer.cpp

![image](https://user-images.githubusercontent.com/12066466/48970914-f547c880-f012-11e8-843e-52cb52f31272.png)

**Comment by mortennobel** [comment]
You are right. The OpenGL context is initialized in Renderer.
(And I was wrong - the hello-engine-raw runs on Windows).

What OpenGL version is supported on your platform?

**Comment by codewing** [comment]
It states:

> OpenGL version 4.2 (Core Profile) Mesa 18.2.5 (4.2)
> sre version 1.1.4

**Comment by mortennobel** [comment]
I have tested on Windows and rendering seem to work. (I added to swapWindow). Could you try running it on Windows or another linux machine to see if it is driver issue?

    void SimpleRenderer::renderFrame() {
      auto rp = sre::RenderPass::create().build();
      rp.drawLines({ {0,0,0},{1,1,1} });
      rp.finish();
      sre::Renderer::instance->swapWindow();
    }

**Comment by codewing** [comment]
On Windows it worked fine but I spotted another error which was unrelated to sre that caused the stack to be messed up and then it crashed after a while in sre.
Thanks for the help!
